version: '3'

services:
  aa_db:
    image: 'postgres:12.0-alpine'
    restart: on-failure:10
    ports:
      - 5452:5432
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
    env_file:
      - ".env"
  aa_server:
    build: '.'
    restart: on-failure:10
    image: 'aa-server:latest'
    volumes:
      - "./alignment_analysis:/src/alignment_analysis"
    depends_on:
      - aa_db
    env_file:
      - ".env"
    ports:
      - 5000:5000
  aa_frontend:
    build: "./alignment_analysis/static"
    restart: on-failure:10
    image: "aa-frontend:latest"
    volumes:
      - "./alignment_analysis/static/:/node/client"

